name: system
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4
#  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.1
  flutter_dotenv: ^5.0.2
  easy_sidemenu: ^0.6.0
#  provider: ^6.1.2
  intl: ^0.20.2
  textfield_search: ^0.11.1
#  pdf
  pdf: ^3.11.1
  printing: ^5.13.4

#  share: ^2.0.4
  path_provider: ^2.1.5
  easy_localization: ^3.0.8
  qr_flutter: ^4.1.0
#  qr: ^3.0.2
#  url_launcher: ^6.3.1
  flutter_speed_dial: ^7.0.0
  syncfusion_flutter_datagrid: ^27.2.5
  fl_chart: ^0.69.2
  connectivity_plus: ^6.1.4
  mobile_scanner: ^6.0.2
#  qr_code_scanner: ^1.0.1


#  flutter_typeahead: ^5.2.0
  autocomplete_textfield_ns: ^2.0.0
  adaptive_scrollbar: ^2.1.2
  table_calendar: ^3.1.3
  open_file: ^3.5.10
  share_plus: ^10.1.4
  file_picker: ^9.0.0
  window_manager: ^0.4.3
  win32: ^5.14.0
  ffi: ^2.1.4
  flutter_pdfview: ^1.4.0
  shimmer: ^3.0.0
  provider: ^6.1.5
#  msix: ^3.16.12

#  firebase_core: ^3.9.0
#  webview_flutter: ^4.10.0
#  charts_flutter: ^0.12.0
#  charts_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  msix: ^3.16.12

msix_config:
  display_name: Rotosh App
  publisher_display_name: Rotosh Company
  identity_name: Rotosh.company.suite.app
  msix_version: 1.0.0.0
  logo_path: C:\Users\pc\Desktop\system\assets\logo\logo-6.png
  capabilities: internetClient, location, microphone, webcam


flutter:


  uses-material-design: true



  assets:
#     - assets/logo/logo-1.jpeg
     - assets/logo/logo-3.png
     - assets/logo/
     - assets/logo/logo-6.png
#     - assets/index.html
#     - images/a_dot_ham.jpeg
     - assets/translations/
     - assets/font/Amiri-Regular.ttf
     - assets/font/Amiri-Bold.ttf
     - assets/logo/logo_00.jpg
